name: Build Wheels

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch
        uses: actions/checkout@v2

      - name: Publish on pypi.org
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          pip install -r requirements.txt
          python setup.py sdist
          python -m pip install -U twine
          python -m twine upload --repository-url https://upload.pypi.org/legacy/ dist/*
